name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CODACY_PROJECT_TOKEN: ${{c30d0e2813bc4bd9aeb2c55e4db4c161}}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Generate Coverage Report
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add your Codecov token in the GitHub secrets
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
